application: polymer-todo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

# All other URLs map directly to their path in dist/.
- url: /
  static_dir: dist
  http_headers:
    Access-Control-Allow-Origin: "*"
  secure: always

skip_files:
- ^(?!dist)(.*)
